# Generated by Django 5.2 on 2025-04-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('detalhe', models.CharField(max_length=255)),
                ('dia_letivo', models.BooleanField(default=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='planner.calendarioletivo')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo', models.TextField(blank=True)),
                ('ementa', models.TextField(blank=True)),
                ('periodo', models.CharField(max_length=20)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='planner.calendarioletivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('objetivos', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='planner.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('etapa', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='planner.disciplina')),
                ('plano_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='planner.planoaula')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='planner.disciplina')),
                ('plano_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='planner.planoaula')),
            ],
        ),
    ]
